### PR TITLE
Blocked on Release - 45921: Add CA Cert field to Snapshots Docs

### PR DESCRIPTION
**Pull request by jonquil2002**
SC: https://app.shortcut.com/replicated/story/45921/blue-team-add-ca-certificate-upload-info-to-snapshots-docs

Preview: https://deploy-preview-270--replicated-docs.netlify.app/enterprise/snapshots-storage-destinations

### CODE REVIEW

**Review by alicenstar — DISMISSED** [review]
Looks great!

**Review by JustinN-Replicated — DISMISSED** [review]

**Review by paigecalvert — APPROVED** [review]
LGTM. Suggestions:
* 3rd-party --> third-party
* Pattern matching on the "(Optional)" tag. Looks like the others put "(optional)" in the "Name" column. I think we could do either, though it should probably match for clarity
* "proxy CA issued certificate" --> This read a little confusingly. Maybe "a proxy certificate issued by a CA"?
* "Only one file can be uploaded, however," --> recommend splitting into two sentences. "..can be uploaded. However, ..."

**Comment by jonquil2002** [comment]
@paigecalvert  Your suggestions have been incorporated and could use a final review/approval. :)

**Review by paigecalvert — APPROVED** [review]
LGTM!

**Pull request merged**
