### PR TITLE
note vendors must install EKCO in embedded clusters

### PR DESCRIPTION
**Pull request by adamancini**

### CODE REVIEW

**Review by paigecalvert — APPROVED** [review]
Thank you @adamancini !

@jonquil2002 , do these edits make sense to you? Also, could be beneficial for us to pair on a sustainable/longer-term way to get all the Kubernetes installer requirements and recommendations into the docs, but this feels definitely feels like a good addition regardless

**Comment by adamancini** [comment]
@paigecalvert @jonquil2002 yeah I think we can work on a longer doc for the "how to choose" that should help in the meantime until Replicated's use of kURL becomes more opinionated

**Comment by paigecalvert** [comment]
@adamancini yes that would be great! One of the updates "on deck" in this area is to provide clearer recommendations as to what data storage and data replication add-ons to use based on various use cases

**Comment by paigecalvert** [comment]
Mergin'!

**Pull request merged**
