### PR TITLE
[1.68.0] WAIT UNTIL RELEASE TO MERGE 45256 adds --required flag

### PR DESCRIPTION
**Pull request by paigecalvert**
SC: https://app.shortcut.com/replicated/story/45256/document-the-ability-to-make-an-app-version-required

CLI doc update for the required releases feature.

### CODE REVIEW

**Comment by ajp-io** [comment]
Lgtm at a glance, but I'd like to see the site preview, but there isn't one here. Do the checks not run for drafts? Was it because GitHub has had issues today? I don't know. But maybe if we hit **Ready for review** it'll run them and we can see the deploy preview.

**Comment by paigecalvert** [comment]
How weird, looks like it's still not previewing. 

Here's my local preview:

Screen Shot 2022-03-24 at 3 33 28 PM

**Review by ajp-io — DISMISSED** [review]
Lgtm. In general do we want the flags to be alphabetized? Should help be in a certain position (top or bottom maybe) or be mixed in with the rest?

**Comment by paigecalvert** [comment]
@ajp-io alphabetized sounds like a great idea--good call

**Review by jonquil2002 — APPROVED** [review]
lgtm

**Pull request merged**
