### PR TITLE
58875: Updated Kubernetes Installer System Requirements

### PR DESCRIPTION
**Pull request by jonquil2002**
SC: https://app.shortcut.com/replicated/story/58875/include-operating-system-requirements-for-kurl-in-documentation

Preview:

https://deploy-preview-671--replicated-docs.netlify.app/enterprise/installing-general-requirements#embedded-cluster-requirements

### CODE REVIEW

**Comment by jonquil2002** [comment]
@chris-sanders PTAL and see if this works better for you. It's for SC https://app.shortcut.com/replicated/story/58875/include-operating-system-requirements-for-kurl-in-documentation. 

The reason that the minimal system requirements are enumerated is because there was another story earlier that asked for the system requirements for KOTS be spelled out in the Replicated docs. Customers were wanting to know what the footprint is without having to go to another docs site. The related story is linked in the SC story above.

**Review by chris-sanders — DISMISSED** [review]
This looks good, I like the explicit call out for these kURL requirements. This should be a lot clearer now and easier to find!

**Review by paigecalvert — DISMISSED** [review]
Very well handled, looks great. Only recommendation is to use colons after the lead-in instead of hyphens, to match the formatting elsewhere (eg existing cluster reqs https://deploy-preview-671--replicated-docs.netlify.app/enterprise/installing-general-requirements#existing-cluster-requirements)

**Comment by jonquil2002** [comment]
@paigecalvert  Just changed those to colons. PTAL Thanks!

**Review by paigecalvert — APPROVED** [review]

**Pull request merged**
