### PR TITLE
Update rn-kubernetes-installer.md

### PR DESCRIPTION
**Pull request by AmberAlston**
Update with missed release note

### CODE REVIEW

**Comment by AmberAlston** [comment]
@emosbaugh Please review per my note in https://app.shortcut.com/replicated/story/60732/remove-beta-k3s-and-rke2-add-ons-and-associated-docs-from-kurl-sh#activity-61226 and fix or approve as you see fit

**Review by jonquil2002 — APPROVED** [review]
lgtm. made a couple of minor style changes

**Comment by AmberAlston** [comment]
Holding until @emosbaugh approves. Tied to an additional update in this story https://app.shortcut.com/replicated/story/60732/remove-beta-k3s-and-rke2-add-ons-and-associated-docs-from-kurl-sh#activity-61295

**Comment by emosbaugh** [comment]
Closing as this will get included in the next release notes https://github.com/replicatedhq/kURL/pull/3675

**Pull request closed without merging**
