### PR TITLE
add initial kots lint rules list

### PR DESCRIPTION
**Pull request by erquhart**
This PR provides initial documentation for [all 40 kots-lint rules](https://github.com/replicatedhq/kots-lint/blob/77505d6f7077a2b73c28efc69489645e15c7a928/pkg/kots/rego/kots-spec-opa-nonrendered.rego).

Using eslint docs as prior art: https://eslint.org/docs/latest/rules/

**Preview of this page:** https://deploy-preview-645--replicated-docs.netlify.app/reference/kots-lint

### CODE REVIEW

**Comment by paigecalvert** [comment]
Thanks @erquhart , give us a shout in #product-docs if you'd like to pair on this

**Comment by erquhart** [comment]
This is about 90% done, planning to complete tomorrow morning.

**Comment by erquhart** [comment]
@paigecalvert @marccampbell @pavansokkenagaraj this is ready for review. Some could use more technical detail or references, but I'd like to prioritize getting an acceptable start merged and improving from there.

**Review by paigecalvert — APPROVED** [review]
@erquhart just added a brief introductory section and bumped the file out a level in the TOC. 

LGTM and I'll do a followup story to make any formatting edits, as we discussed this morning

Thanks again!

**Pull request merged**
