### PR TITLE
Tweak wording

### PR DESCRIPTION
**Pull request by ajp-io**

### CODE REVIEW

**Review by paigecalvert — DISMISSED** [review]
LGTM @ajp-io 
(btw, if we miss PRs, add @replicatedhq/replicated-docs and/or ping us in slack)

**Comment by ajp-io** [comment]
Oh I was having a discussion with Jonquil about this one, but I don't think we finished. But if you approved, that's fine too.

**Comment by ajp-io** [comment]
Looks like you dismissed your review though, if you were looking to approve it.

**Comment by paigecalvert** [comment]
@ajp-io oh my bad, I missed the slack convo. There was a merge conflict that I resolved after the initial approval, which dismissed my original review. Was just waiting for it to finish building to re-approve.

**Review by paigecalvert — APPROVED** [review]

**Pull request merged**
