### PR TITLE
DO NOT MERGE - chore: Replace troubleshoot.io with troubleshoot.sh

### PR DESCRIPTION
**Pull request by banjoh**
Motivation of this change can be found [here](https://github.com/replicatedhq/troubleshoot/issues/1070)

The is related to https://github.com/replicatedhq/troubleshoot.sh/pull/480

### CODE REVIEW

**Comment by xavpaice** [comment]
@banjoh see https://github.com/replicatedhq/troubleshoot/issues/1164

**Comment by xavpaice** [comment]
As of v0.69.0 of Troubleshoot, this label is supported.  We should have this version in KOTS before merging this PR

**Comment by xavpaice** [comment]
ref: https://github.com/replicatedhq/troubleshoot/issues/1070

**Comment by paigecalvert** [comment]
Hi @banjoh and @xavpaice ! Wanted to check on this PR since it's been open awhile. Is this still something that we plan to merge or should we close it out?

**Comment by xavpaice** [comment]
Closing this now, the changes were merged elsewhere.

**Pull request closed without merging**
