### PR TITLE
HOLD FOR CLARIFICATION: Update _statusesTable.mdx

### PR DESCRIPTION
**Pull request by dexhorthy**

### CODE REVIEW

**Comment by dexhorthy** [comment]
@paigecalvert FYI @divolgin should be the Subject Matter Expert to review this, not me, and he's not available to do so today

**Review by paigecalvert — APPROVED** [review]
Approving, and will wait to merge until @divolgin is able to review. I'll follow up tomorrow

**Comment by dexhorthy** [comment]
sounds like this might be wrong. Might be a day or two until we address

**Comment by paigecalvert** [comment]
Going to close this out. We can reopen as needed!

**Pull request closed without merging**
