### PR TITLE
HOLD FOR RELEASE: Document PrivateCACert template function

### PR DESCRIPTION
**Pull request by laverya**

### CODE REVIEW

**Review by paigecalvert — DISMISSED** [review]
@laverya looks good--just relocated it so it's in alphabetical order and then edited the last sentence (LMK if it still reflects what you were trying to get across or not)

**Comment by laverya** [comment]
As currently implemented @paigecalvert it will return the configmap name even if there are no entries in the configmap

**Comment by paigecalvert** [comment]
@laverya gotcha thanks; reworded

**Review by paigecalvert — APPROVED** [review]

**Review by ajp-io — APPROVED** [review]
Open to any suggestions, @replicatedhq/replicated-docs. I'm also not sure about the ordering of the functions on this page. This one is kind of in alphabetical order…

**Comment by paigecalvert** [comment]
@ajp-io I'll merge this and then alphabetize the template functions in the other PR I'm doing to remove the deprecated items

**Comment by ajp-io** [comment]
Ok, don't merge yet! Waiting on a release. I'll update the PR title.

**Pull request merged**
