### PR TITLE
Add Google Artifact Registry and custom-id

### PR DESCRIPTION
**Pull request by FourSigma**
* Add Google Artifact Registry to `replicated registry add` command
    - Google Artifact Registry supports both service account and OAuth  token based authentication
    
* Updated docs for creating new customers with `--custom-id my-salesforce-id` parameter
    - Updates `replicated customer ls` to display new `CUSTOM_ID` column

### CODE REVIEW

**Comment by AmberAlston** [comment]
PR looks good but we do need a release note still for both of these CLI updates

**Comment by FourSigma** [comment]
> PR looks good but we do need a release note still for both of these CLI updates

Thanks @paigecalvert.  Are these release notes in the Replicated CLI repo not sufficient? https://github.com/replicatedhq/replicated/releases/tag/v0.68.0?

**Comment by paigecalvert** [comment]
> > PR looks good but we do need a release note still for both of these CLI updates
> 
> Thanks @paigecalvert.  Are these release notes in the Replicated CLI repo not sufficient? https://github.com/replicatedhq/replicated/releases/tag/v0.68.0?

I think @AmberAlston left that comment, @FourSigma 🙂 . And I reckon she's just referring to adding the release note for them to the Replicated docs as well

**Comment by FourSigma** [comment]
> > > PR looks good but we do need a release note still for both of these CLI updates
> > 
> > 
> > Thanks @paigecalvert.  Are these release notes in the Replicated CLI repo not sufficient? https://github.com/replicatedhq/replicated/releases/tag/v0.68.0?
> 
> I think @AmberAlston left that comment, @FourSigma 🙂 . And I reckon she's just referring to adding the release note for them to the Replicated docs as well

*Slaps forehead*. Thanks @paigecalvert.  One thing I noticed about the Vendor Portal release notes is that we do not log Replicated CLI changes.  Additionally, the backend API changes were already logged in the VP release docs (see Feb 9th and Feb. 14th).

**Review by AmberAlston — APPROVED** [review]

**Comment by AmberAlston** [comment]
I'm good with this as-is. See RN discussion over in this comment - https://app.shortcut.com/replicated/story/98503/cli-can-set-a-custom-id-when-creating-customer#activity-99849

@paigecalvert do you want to look at this before I merge it?

**Pull request merged**
